# Generated by Django 3.1 on 2020-08-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='sentence',
            new_name='sentance',
        ),
    ]
